/**
 * Analytics Metrics Definitions
 *
 * Comprehensive definitions of all analytics metrics used across the system.
 * This serves as a single source of truth for metric calculations and descriptions.
 */

// ============================================
// METRIC DEFINITIONS
// ============================================

export interface MetricDefinition {
  id: string;
  name: string;
  description: string;
  category: 'revenue' | 'customer' | 'product' | 'order' | 'marketing' | 'operational';
  formula: string;
  sqlExpression: string;
  format: 'currency' | 'number' | 'percentage' | 'decimal' | 'duration';
  aggregation: 'SUM' | 'AVG' | 'COUNT' | 'MIN' | 'MAX' | 'MEDIAN';
  unit?: string;
  example?: string;
}

export const ANALYTICS_METRICS: Record<string, MetricDefinition> = {
  // ============================================
  // REVENUE METRICS
  // ============================================

  total_revenue: {
    id: 'total_revenue',
    name: 'Total Revenue',
    description: 'Sum of all order totals (excluding cancelled/refunded)',
    category: 'revenue',
    formula: 'SUM(order.total)',
    sqlExpression: 'SUM(total)',
    format: 'currency',
    aggregation: 'SUM',
    unit: 'USD',
    example: '$125,430.50'
  },

  gross_profit: {
    id: 'gross_profit',
    name: 'Gross Profit',
    description: 'Revenue minus cost of goods sold',
    category: 'revenue',
    formula: 'SUM(order.total - order.cost)',
    sqlExpression: 'SUM(total - total_cost)',
    format: 'currency',
    aggregation: 'SUM',
    unit: 'USD',
    example: '$45,230.80'
  },

  profit_margin: {
    id: 'profit_margin',
    name: 'Profit Margin',
    description: 'Gross profit as a percentage of revenue',
    category: 'revenue',
    formula: '(Gross Profit / Total Revenue) * 100',
    sqlExpression: '((SUM(total - total_cost) / SUM(total)) * 100)',
    format: 'percentage',
    aggregation: 'AVG',
    unit: '%',
    example: '36.05%'
  },

  avg_order_value: {
    id: 'avg_order_value',
    name: 'Average Order Value (AOV)',
    description: 'Average value per order',
    category: 'revenue',
    formula: 'Total Revenue / Total Orders',
    sqlExpression: 'AVG(total)',
    format: 'currency',
    aggregation: 'AVG',
    unit: 'USD',
    example: '$366.76'
  },

  // ============================================
  // CUSTOMER METRICS
  // ============================================

  total_customers: {
    id: 'total_customers',
    name: 'Total Customers',
    description: 'Total number of unique customers',
    category: 'customer',
    formula: 'COUNT(DISTINCT customer_id)',
    sqlExpression: 'COUNT(DISTINCT customer_id)',
    format: 'number',
    aggregation: 'COUNT',
    example: '1,245'
  },

  new_customers: {
    id: 'new_customers',
    name: 'New Customers',
    description: 'Number of customers who made their first purchase in the period',
    category: 'customer',
    formula: 'COUNT(customers with first_order_date in period)',
    sqlExpression: 'COUNT(*)',
    format: 'number',
    aggregation: 'COUNT',
    example: '45'
  },

  customer_lifetime_value: {
    id: 'customer_lifetime_value',
    name: 'Customer Lifetime Value (CLV)',
    description: 'Total revenue generated by a customer over their lifetime',
    category: 'customer',
    formula: 'SUM(all orders for customer)',
    sqlExpression: 'SUM(total_spent)',
    format: 'currency',
    aggregation: 'AVG',
    unit: 'USD',
    example: '$1,240.50'
  },

  predicted_clv: {
    id: 'predicted_clv',
    name: 'Predicted CLV',
    description: 'Predicted future value of customer over 3 years',
    category: 'customer',
    formula: 'AOV × Purchase Frequency × Customer Lifespan',
    sqlExpression: '(avg_order_value * (total_orders / customer_age_years) * 3)',
    format: 'currency',
    aggregation: 'AVG',
    unit: 'USD',
    example: '$3,450.00'
  },

  customer_retention_rate: {
    id: 'customer_retention_rate',
    name: 'Customer Retention Rate',
    description: 'Percentage of customers who made repeat purchases',
    category: 'customer',
    formula: '(Active Customers / Total Customers) * 100',
    sqlExpression: '((COUNT(CASE WHEN days_since_last_order <= 90 THEN 1 END)::float / COUNT(*)) * 100)',
    format: 'percentage',
    aggregation: 'AVG',
    unit: '%',
    example: '68.5%'
  },

  churn_rate: {
    id: 'churn_rate',
    name: 'Churn Rate',
    description: 'Percentage of customers who stopped purchasing',
    category: 'customer',
    formula: '(Churned Customers / Total Customers) * 100',
    sqlExpression: '((COUNT(CASE WHEN days_since_last_order > 90 THEN 1 END)::float / COUNT(*)) * 100)',
    format: 'percentage',
    aggregation: 'AVG',
    unit: '%',
    example: '31.5%'
  },

  // ============================================
  // RFM METRICS
  // ============================================

  recency_score: {
    id: 'recency_score',
    name: 'Recency Score',
    description: 'Score (1-5) based on how recently customer made a purchase',
    category: 'customer',
    formula: 'Scored based on days since last order',
    sqlExpression: 'CASE WHEN days_since_last_order <= 30 THEN 5 WHEN days_since_last_order <= 90 THEN 4 ELSE 1 END',
    format: 'number',
    aggregation: 'AVG',
    example: '4'
  },

  frequency_score: {
    id: 'frequency_score',
    name: 'Frequency Score',
    description: 'Score (1-5) based on number of purchases',
    category: 'customer',
    formula: 'Scored based on total orders',
    sqlExpression: 'CASE WHEN total_orders >= 20 THEN 5 WHEN total_orders >= 10 THEN 4 ELSE 1 END',
    format: 'number',
    aggregation: 'AVG',
    example: '3'
  },

  monetary_score: {
    id: 'monetary_score',
    name: 'Monetary Score',
    description: 'Score (1-5) based on total spending',
    category: 'customer',
    formula: 'Scored based on total spent',
    sqlExpression: 'CASE WHEN total_spent >= 10000 THEN 5 WHEN total_spent >= 5000 THEN 4 ELSE 1 END',
    format: 'number',
    aggregation: 'AVG',
    example: '4'
  },

  // ============================================
  // ORDER METRICS
  // ============================================

  total_orders: {
    id: 'total_orders',
    name: 'Total Orders',
    description: 'Total number of orders placed',
    category: 'order',
    formula: 'COUNT(orders)',
    sqlExpression: 'COUNT(*)',
    format: 'number',
    aggregation: 'COUNT',
    example: '342'
  },

  completed_orders: {
    id: 'completed_orders',
    name: 'Completed Orders',
    description: 'Number of successfully completed orders',
    category: 'order',
    formula: 'COUNT(orders WHERE status = completed)',
    sqlExpression: 'COUNT(CASE WHEN status = \'completed\' THEN 1 END)',
    format: 'number',
    aggregation: 'COUNT',
    example: '298'
  },

  order_completion_rate: {
    id: 'order_completion_rate',
    name: 'Order Completion Rate',
    description: 'Percentage of orders successfully completed',
    category: 'order',
    formula: '(Completed Orders / Total Orders) * 100',
    sqlExpression: '((COUNT(CASE WHEN status = \'completed\' THEN 1 END)::float / COUNT(*)) * 100)',
    format: 'percentage',
    aggregation: 'AVG',
    unit: '%',
    example: '87.1%'
  },

  avg_items_per_order: {
    id: 'avg_items_per_order',
    name: 'Average Items per Order',
    description: 'Average number of items in each order',
    category: 'order',
    formula: 'Total Items / Total Orders',
    sqlExpression: 'AVG(total_items)',
    format: 'decimal',
    aggregation: 'AVG',
    example: '2.3'
  },

  avg_delivery_time: {
    id: 'avg_delivery_time',
    name: 'Average Delivery Time',
    description: 'Average time from order to delivery in days',
    category: 'order',
    formula: 'AVG(delivered_at - created_at)',
    sqlExpression: 'AVG(delivery_days)',
    format: 'decimal',
    aggregation: 'AVG',
    unit: 'days',
    example: '3.5 days'
  },

  // ============================================
  // PRODUCT METRICS
  // ============================================

  total_products_sold: {
    id: 'total_products_sold',
    name: 'Total Products Sold',
    description: 'Total quantity of products sold',
    category: 'product',
    formula: 'SUM(quantity)',
    sqlExpression: 'SUM(total_quantity_sold)',
    format: 'number',
    aggregation: 'SUM',
    example: '1,234'
  },

  unique_products_sold: {
    id: 'unique_products_sold',
    name: 'Unique Products Sold',
    description: 'Number of unique products sold',
    category: 'product',
    formula: 'COUNT(DISTINCT product_id)',
    sqlExpression: 'COUNT(DISTINCT product_id)',
    format: 'number',
    aggregation: 'COUNT',
    example: '89'
  },

  product_revenue: {
    id: 'product_revenue',
    name: 'Product Revenue',
    description: 'Total revenue generated by product sales',
    category: 'product',
    formula: 'SUM(price × quantity)',
    sqlExpression: 'SUM(total_revenue)',
    format: 'currency',
    aggregation: 'SUM',
    unit: 'USD',
    example: '$125,430.50'
  },

  inventory_turnover: {
    id: 'inventory_turnover',
    name: 'Inventory Turnover',
    description: 'Rate at which inventory is sold and replaced',
    category: 'product',
    formula: 'Cost of Goods Sold / Average Inventory',
    sqlExpression: '(quantity_sold_30d / 30.0)',
    format: 'decimal',
    aggregation: 'AVG',
    example: '12.5'
  },

  // ============================================
  // MARKETING METRICS
  // ============================================

  conversion_rate: {
    id: 'conversion_rate',
    name: 'Conversion Rate',
    description: 'Percentage of visitors who make a purchase',
    category: 'marketing',
    formula: '(Orders / Visitors) * 100',
    sqlExpression: '((completed_orders::float / total_visitors) * 100)',
    format: 'percentage',
    aggregation: 'AVG',
    unit: '%',
    example: '3.8%'
  },

  cart_abandonment_rate: {
    id: 'cart_abandonment_rate',
    name: 'Cart Abandonment Rate',
    description: 'Percentage of carts abandoned before checkout',
    category: 'marketing',
    formula: '(Abandoned Carts / Total Carts) * 100',
    sqlExpression: '((abandoned_carts::float / total_carts) * 100)',
    format: 'percentage',
    aggregation: 'AVG',
    unit: '%',
    example: '68.5%'
  },

  customer_acquisition_cost: {
    id: 'customer_acquisition_cost',
    name: 'Customer Acquisition Cost (CAC)',
    description: 'Cost to acquire a new customer',
    category: 'marketing',
    formula: 'Total Marketing Spend / New Customers',
    sqlExpression: '(total_marketing_spend / new_customers)',
    format: 'currency',
    aggregation: 'AVG',
    unit: 'USD',
    example: '$45.00'
  },

  // ============================================
  // OPERATIONAL METRICS
  // ============================================

  fulfillment_rate: {
    id: 'fulfillment_rate',
    name: 'Fulfillment Rate',
    description: 'Percentage of orders successfully fulfilled',
    category: 'operational',
    formula: '(Fulfilled Orders / Total Orders) * 100',
    sqlExpression: '((fulfilled_orders::float / total_orders) * 100)',
    format: 'percentage',
    aggregation: 'AVG',
    unit: '%',
    example: '95.2%'
  },

  return_rate: {
    id: 'return_rate',
    name: 'Return Rate',
    description: 'Percentage of orders returned',
    category: 'operational',
    formula: '(Returned Orders / Total Orders) * 100',
    sqlExpression: '((returned_orders::float / total_orders) * 100)',
    format: 'percentage',
    aggregation: 'AVG',
    unit: '%',
    example: '2.5%'
  },

  stock_availability: {
    id: 'stock_availability',
    name: 'Stock Availability',
    description: 'Percentage of products in stock',
    category: 'operational',
    formula: '(In Stock Products / Total Products) * 100',
    sqlExpression: '((COUNT(CASE WHEN stock > 0 THEN 1 END)::float / COUNT(*)) * 100)',
    format: 'percentage',
    aggregation: 'AVG',
    unit: '%',
    example: '92.3%'
  }
};

// ============================================
// DIMENSION DEFINITIONS
// ============================================

export interface DimensionDefinition {
  id: string;
  name: string;
  description: string;
  category: 'time' | 'customer' | 'product' | 'order' | 'location';
  dataType: 'string' | 'number' | 'date' | 'boolean';
  examples: string[];
}

export const ANALYTICS_DIMENSIONS: Record<string, DimensionDefinition> = {
  // Time dimensions
  date: {
    id: 'date',
    name: 'Date',
    description: 'Specific date',
    category: 'time',
    dataType: 'date',
    examples: ['2024-01-15', '2024-02-20']
  },

  week: {
    id: 'week',
    name: 'Week',
    description: 'Week number',
    category: 'time',
    dataType: 'string',
    examples: ['2024-W03', '2024-W15']
  },

  month: {
    id: 'month',
    name: 'Month',
    description: 'Month',
    category: 'time',
    dataType: 'string',
    examples: ['2024-01', '2024-02']
  },

  quarter: {
    id: 'quarter',
    name: 'Quarter',
    description: 'Quarter',
    category: 'time',
    dataType: 'string',
    examples: ['2024-Q1', '2024-Q2']
  },

  year: {
    id: 'year',
    name: 'Year',
    description: 'Year',
    category: 'time',
    dataType: 'number',
    examples: ['2023', '2024']
  },

  // Customer dimensions
  customer_segment: {
    id: 'customer_segment',
    name: 'Customer Segment',
    description: 'Customer segmentation category',
    category: 'customer',
    dataType: 'string',
    examples: ['Champions', 'Loyal Customers', 'At Risk', 'New Customers']
  },

  rfm_segment: {
    id: 'rfm_segment',
    name: 'RFM Segment',
    description: 'RFM score combination',
    category: 'customer',
    dataType: 'string',
    examples: ['555', '444', '111']
  },

  // Product dimensions
  product_category: {
    id: 'product_category',
    name: 'Product Category',
    description: 'Product category',
    category: 'product',
    dataType: 'string',
    examples: ['Electronics', 'Clothing', 'Home & Garden']
  },

  product_name: {
    id: 'product_name',
    name: 'Product Name',
    description: 'Product name',
    category: 'product',
    dataType: 'string',
    examples: ['iPhone 13', 'Nike Air Max', 'Coffee Maker']
  },

  // Order dimensions
  order_channel: {
    id: 'order_channel',
    name: 'Order Channel',
    description: 'Sales channel',
    category: 'order',
    dataType: 'string',
    examples: ['Online', 'In-Store', 'Mobile App', 'Marketplace']
  },

  order_status: {
    id: 'order_status',
    name: 'Order Status',
    description: 'Order status',
    category: 'order',
    dataType: 'string',
    examples: ['pending', 'processing', 'completed', 'cancelled']
  },

  payment_method: {
    id: 'payment_method',
    name: 'Payment Method',
    description: 'Payment method used',
    category: 'order',
    dataType: 'string',
    examples: ['Credit Card', 'PayPal', 'Bank Transfer']
  }
};

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Get all metrics in a specific category
 */
export function getMetricsByCategory(category: MetricDefinition['category']): MetricDefinition[] {
  return Object.values(ANALYTICS_METRICS).filter((m) => m.category === category);
}

/**
 * Get all dimensions in a specific category
 */
export function getDimensionsByCategory(category: DimensionDefinition['category']): DimensionDefinition[] {
  return Object.values(ANALYTICS_DIMENSIONS).filter((d) => d.category === category);
}

/**
 * Format metric value based on its format type
 */
export function formatMetricValue(value: number, format: MetricDefinition['format']): string {
  if (value === null || value === undefined) return '-';

  switch (format) {
    case 'currency':
      return `$${value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    case 'percentage':
      return `${value.toFixed(2)}%`;
    case 'decimal':
      return value.toFixed(2);
    case 'duration':
      return `${value.toFixed(1)} days`;
    case 'number':
    default:
      return value.toLocaleString();
  }
}

/**
 * Get metric by ID
 */
export function getMetric(id: string): MetricDefinition | undefined {
  return ANALYTICS_METRICS[id];
}

/**
 * Get dimension by ID
 */
export function getDimension(id: string): DimensionDefinition | undefined {
  return ANALYTICS_DIMENSIONS[id];
}
